spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: root
  jpa:
    genrate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/




server:
  port: 9004
